### ISSUE TITLE
registryIdRef not working in Replication resource

### ISSUE THREAD

**Issue by tschlaepfer** [globallogicuki/provider-harbor#4]
Hi All

Testing the Replication resource using the registryIdRef showed that the reference to a Registry object seems not to work. 

![image](https://github.com/user-attachments/assets/d2e2f204-6f5b-401b-a585-db6fd3802154)

Looking at the code I suspect the issue is that the referencing code is not fetching the right property from the referenced object. 

In https://github.com/globallogicuki/provider-harbor/blob/main/config/replication/config.go the reference is specified but does not have a custom Extractor to reference the right parameter in the Registry object which would be "registryId", see screenshot.
![image](https://github.com/user-attachments/assets/44f08d2c-29ba-4dba-8ce3-8bb2b23bd7ac)

By default, the reference fetches the "id" parameter of a referenced object.

**Comment by lornest** [comment]
Hey @tschlaepfer. Thanks for raising the issue. Let me take a look at this and get back to you.

**Comment by lornest** [comment]
This should work as per other references like in project member group https://github.com/globallogicuki/provider-harbor/blob/main/config/membergroup/config.go

I've been able to replicate your issue locally, so trying to figure out what the problem is...

**Comment by tschlaepfer** [comment]
Hi @lornest thanks for looking into it. I also had a look this morning, and while it proved to be more challenging than I expected, I eventually found a way to fix the registryIdRef. 

As I mentioned in the issue report, I expect that by default the reference is done to the "id" parameter of the referenced object which in the screenshot example would be /registries/1. If you create a custom Extractor and add this to the reference configuration you can then extract the correct parameter which is "registryId". I struggled a bit with getting the value because it is not straightforward as the value in "registryId" is not a string but rather a float64. However, in the end, I managed to get the extractor code to fetch the "registryId" parameter properly. 

I tested it by running the provider locally against my cluster with Harbor in it. Here is a screenshot from creating a Replication object using registryIdSelector.

![image](https://github.com/user-attachments/assets/78845c52-7655-4e4b-8474-8a10bdc55add)

In addition to fixing the replication, I also added the code to reference registries in Project so that one can create cache proxy repositories :) Here is a screenshot from my test to create a cache proxy project using registryIdRef

![image](https://github.com/user-attachments/assets/96738527-9625-416d-9f3d-8d3da656428d)

I will supply you the code via pull request, let me know if I should improve or update anything, I'm not an experienced Go developer so my code may need some improvement.

**Comment by lornest** [comment]
Thanks for raising this PR @tschlaepfer. I'll need to take a look at it when I get some time today. Will let you know when the new provider version is ready.

**Comment by lornest** [comment]
@tschlaepfer this and issue 6 have just been released. I'll take a look at the other one you raised for the next release. Thanks!
